export const PATH = {
  // GUEST MODULE
  HOME: '/',
  LANDING_PAGE: '/landing-page',
  PRICING_PAGE: '/pricing-page',
  CONTACT_PAGE: '/contact-page',
  // AUTH MODULE
  AUTH: '/auth',
  LOGIN: '/auth/login',
  FIRST_LOGIN: '/auth/first-login',
  FORGOT_PASSWORD: '/auth/forgot-password',
  RESET_PASSWORD: '/auth/reset-password',
  REGISTER: '/auth/register',
  // SUPER ADMIN
  SUPER_ADMIN: '/super-admin',
  SUPER_ADMIN_DASHBOARD: '/super-admin/dashboard',
  SUPER_ADMIN_USERS: '/super-admin/users',
  SUPER_ADMIN_ORDERS: '/super-admin/orders',
  SUPER_ADMIN_PAYMENTS: '/super-admin/payments',
  SUPER_ADMIN_PACKAGES: '/super-admin/packages',
  SUPER_ADMIN_FEATURES: '/super-admin/features',
  SUPER_ADMIN_CONSULTATION_REQ: '/super-admin/consultation-requests',
  SUPER_ADMIN_WORKSPACES: '/super-admin/workspaces',
  SUPER_ADMIN_WORKSPACE_DETAIL: '/super-admin/workspace-detail/:id',
  // HR - ADMIN WORKSPACE (admin-ws)
  ADMIN: '/admin-ws',
  ADMIN_DASHBOARD: '/admin-ws/dashboard',
  ADMIN_MY_WORKSPACE: '/admin-ws/my-workspace',
  ADMIN_MY_EMPLOYEES: '/admin-ws/my-employees',
  ADMIN_MY_REPORT: '/admin-ws/my-reports',
  ADMIN_DEPARTMENTS: '/admin-ws/departments',
  ADMIN_MY_EMPLOYEE_DETAIL: '/admin-ws/my-employee-detail/:id',
  ADMIN_MY_PROJECTS: '/admin-ws/my-projects',
  ADMIN_MY_PROJECT_DETAIL: '/admin-ws/my-project-detail/:id',
  ADMIN_SETTINGS: '/admin-ws/account-settings',
  ADMIN_NOTIFICATIONS: '/admin-ws/notifications',
  // EMPLOYEE (emp)
  EMPLOYEE: '/emp',
  EMPLOYEE_SETTINGS: '/emp/account-settings',
  EMPLOYEE_KANBAN: '/emp/kanban-board',
  EMPLOYEE_MY_TEAM: '/emp/my-team',
  EMPLOYEE_MY_FILES: '/emp/my-files',
  EMPLOYEE_NOTIFICATIONS: '/emp/notifications',
  EMPLOYEE_MY_TASKS: '/emp/my-tasks',
  EMPLOYEE_MY_PERFORMANCE: '/emp/my-performance',
  // TEAM LEADER
  EMPLOYEE_MANAGER: '/mng',
  EMPLOYEE_MANAGE_PROJECTS: '/mng/my-projects',
  EMPLOYEE_MANAGE_MY_TASKS: '/mng/my-tasks',
  EMPLOYEE_MANAGE_KANBAN: '/mng/kanban-board',
  EMPLOYEE_MANAGE_MY_TEAM: '/mng/my-team',
  EMPLOYEE_MANAGE_MY_TEAM_DETAIL: '/mng/my-team/:id',
  EMPLOYEE_MANAGE_MY_PERFORMANCE: '/mng/my-performance',
  EMPLOYEE_MANAGE_MY_FILES: '/mng/my-files',
  EMPLOYEE_MANAGE_BACKLOG: '/mng/backlog',
  EMPLOYEE_MANAGE_NOTIFICATIONS: '/mng/notifications',
  EMPLOYEE_MANAGE_SETTINGS: '/mng/account-settings',
  // EMPLOYEE_LEAD: '/emp/team-lead',
  // EMPLOYEE_STAFF: '/emp/staff',
  FORBIDDEN: '/403',
  NOTFOUND: '/404'
}
